version: 1.0.{build}
image: Ubuntu

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- sh: "which python3.8"
- sh: "which python3.6"
- sh: "which python3.7"
- sh: "which python2.7"
- sh: "PATH=$PATH:/usr/bin/python3.8:/usr/bin/python3.7"
- pip install tox --user
- make init

test_script:
- tox
