version: 1.0.{build}
image: Ubuntu

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- sh: pip install tox --user
- sh: "PATH=/home/appveyor/.local/bin:$PATH"
- sh: echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
- sh: make init
test_script:
- tox
